---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
     argocd.argoproj.io/sync-wave: "3"
  name: "{{ .Values.environmentName }}-{{ .Values.applicationName }}"
  namespace: openshift-gitops
spec:
  ignoreDifferences:
  - group: "apps"
    kind: "DeploymentConfig"
    jsonPointers:
    - /spec/containers/image
  destination:
    namespace: "{{ .Values.environmentName }}-dev"
    server: https://kubernetes.default.svc
  project: {{ .Values.environmentName }}-project
  source:
    path: {{ .Values.gitrepoPath }}
    repoURL: {{ .Values.gitrepoName }}
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
