---
kind: ConfigMap
apiVersion: v1
metadata:
  name: argocd-rbac-cm
  namespace: {{ $.Values.environmentName }}-argo
  labels:
    app.kubernetes.io/managed-by: argocd-{{ $.Values.environmentName }}
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
data:
  policy.csv: |
    g, system:cluster-admins, role:admin
    g, system:{{ $.Values.environmentName }}-argo role:readonly
  policy.default: ''
  scopes: '[groups]'
