---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops
    kubernetes.io/metadata.name: "{{ .Values.environmentName }}"
  name: "{{ .Values.environmentName }}-test"
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec: {}

