apiVersion: v1
kind: Namespace
metadata:
  annotations:
  labels:
    kubernetes.io/metadata.name: {{ .Values.environmentName }}-dev 
    platform/owner: {{ .Values.customerName }} 
  name: {{ .Values.environmentName }}-dev
