apiVersion: v1
kind: Namespace
metadata:
  annotations:
  labels:
    kubernetes.io/metadata.name: {{ .Values.environmentName }}-prod 
    platform/owner: {{ .Values.customerName }}
  name: {{ .Values.environmentName }}-prod
