{{- range $.Values.namespacePostfixes }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-from-openshift-monitor
  namespace: {{ $.Values.environmentName }}-{{ . }}
  labels:
    platform/owner: {{ $.Values.customerName }}
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          network.openshift.io/policy-group: monitoring
  podSelector: {}
  policyTypes:
  - Ingress
{{- end }}
