{{- range $.Values.namespacePostfixes }}
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: deny-by-default
  namespace: {{ $.Values.environmentName }}-{{ . }}
  labels:
    platform/owner: {{ $.Values.customerName }}
spec:
  podSelector: {}
  ingress: []
{{- end }}

