kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-same-namespace
  namespace: {{ .Values.environmentName }}-prod
  labels:
    platform/owner: {{ .Values.customerName }}
spec:
  podSelector: {}
  ingress:
  - from:
    - podSelector: {}
