{{- range $.Values.namespacePostfixes }}
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: admin-{{ $.Values.environmentName }}-dev-access
  namespace: {{ $.Values.environmentName }}-{{ . }}
  labels:
    kubernetes.io/metadata.name: {{ $.Values.environmentName }}-{{ . }}
    platform/owner: {{ $.Values.customerName }}
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: {{ $.Values.groupNameAdmin }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
{{- end }}
