apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: testapplication
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: testapp
  source:
    path: charts/controller-branch
    repoURL: https://github.com/kborup-redhat/gitops.git
    targetRevision: main
    helm:
      parameters: 
      - name: environmentName
        value: testapp123
      - name: customerName
        value: testcustomer
      - name: dockerFile
        value: ".dockerconfigjson: ewogICAiYXV0aHMiOnsKICAgICAgImNsb3VkLm9wZW5zaGlmdC5jb20iOnsKICAgICAgICAgImF1dGgiOiJiM0JsYj0iLAogICAgICAgICAiZW1haWwiOiJ5b3VAZXhhbXBsZS5jb20iCiAgICAgIH0sCiAgICAgICJxdWF5LmlvIjp7CiAgICAgICAgICJhdXRoIjoiYjNCbGI9IiwKICAgICAgICAgImVtYWlsIjoieW91QGV4YW1wbGUuY29tIgogICAgICB9LAogICAgICAicXVheS5pby9yZXBvc2l0b3J5LW1haW4iOnsKICAgICAgICAgImF1dGgiOiJiM0JsYj0iLAogICAgICAgICAiZW1haWwiOiJ5b3VAZXhhbXBsZS5jb20iCiAgICAgIH0KICAgfQp9Cg==" 
      - name: groupNameAdmin
        value: gruppenavn1
      - name: namespacePostfixes
        value: {dev,test,prod,argo}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
